packages:
  - core
  - backend-a
  - backend-b
  - frontend
allowBuilds:
  '@google/genai': false
  '@mongodb-js/zstd': false
  core-js-pure: false
  esbuild: true
  node-liblzma: false
  protobufjs: false
  sharp: false
  workerd: true
patchedDependencies:
  '@durable-streams/client@0.2.6': patches/@durable-streams__client@0.2.6.patch
  '@flue/cli@1.0.0-beta.9': patches/@flue__cli@1.0.0-beta.9.patch
